/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs.ia.music_mng_sys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lakshya
 */
public class billpage extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
ResultSet rs2=null;
ResultSet rs3=null;
//Statement stmt=null;
    /**
     * Creates new form billpage
     */
    public billpage() {
        initComponents();
        show1();
        
       
        try

        {
            Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            String sql="select * from products";

            PreparedStatement pst=con.prepareStatement(sql);

            rs=pst.executeQuery();
            int i=0;
           while(rs.next())
            {
                String name= rs.getString("prod_name");
                productbox.addItem(name);
                    
         }
           productbox.setSelectedItem("");
           }
            catch(Exception e)

        {

            JOptionPane.showMessageDialog(null,e);
        }
        show1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userlabel4 = new javax.swing.JLabel();
        userlabel1 = new javax.swing.JLabel();
        userlabel5 = new javax.swing.JLabel();
        userlabel2 = new javax.swing.JLabel();
        userlabel3 = new javax.swing.JLabel();
        userlabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        billID = new javax.swing.JTextField();
        billdate = new javax.swing.JTextField();
        userlabel7 = new javax.swing.JLabel();
        userlabel8 = new javax.swing.JLabel();
        userlabel9 = new javax.swing.JLabel();
        userlabel10 = new javax.swing.JLabel();
        userlabel11 = new javax.swing.JLabel();
        productbox = new javax.swing.JComboBox<>();
        userlabel12 = new javax.swing.JLabel();
        customerphone = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        paymode = new javax.swing.JComboBox<>();
        billsearch = new javax.swing.JTextField();
        suppliersearchbox = new javax.swing.JButton();
        backbutton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        userlabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel4.setText("Phone:");

        userlabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel1.setText("Address:");

        userlabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel5.setText("Email:");

        userlabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel2.setText("ID:");

        userlabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel3.setText("First name:");

        userlabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel6.setText("Last name:");

        jButton7.setText("SAVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setText("DELETE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        billID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billIDActionPerformed(evt);
            }
        });

        userlabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel7.setText("Payment method:");

        userlabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel8.setText("Amount:");

        userlabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel9.setText("Bill date:");

        userlabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel10.setText("Bill ID:");

        userlabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel11.setText("Product:");

        productbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productboxActionPerformed(evt);
            }
        });

        userlabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel12.setText("Customer phone:");

        customerphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerphoneActionPerformed(evt);
            }
        });

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Date", "Customer name", "Product name", "Amount", "Payment mode"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        paymode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cash", "Card", "UPI" }));
        paymode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymodeActionPerformed(evt);
            }
        });

        billsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsearchActionPerformed(evt);
            }
        });

        suppliersearchbox.setText("SEARCH");
        suppliersearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersearchboxActionPerformed(evt);
            }
        });

        backbutton1.setText("BACK");
        backbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton1ActionPerformed(evt);
            }
        });

        jButton1.setText("SIGN OUT");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(billsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(suppliersearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userlabel10)
                                    .addComponent(userlabel11)
                                    .addComponent(userlabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel12)
                                    .addComponent(userlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel8))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(billID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(paymode, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(customerphone, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(amount, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(productbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 144, Short.MAX_VALUE))
                                    .addComponent(billdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suppliersearchbox)
                            .addComponent(billsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billdate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerphone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
public void search_bills(){
DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                 model.setRowCount(0);
              String D=billsearch.getText();
        try
        {
            Class.forName("java.sql.Driver");

            ResultSet rs=null;

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            if (D.startsWith("id:")){
              String sql="select * from bills where bill_id=?";
                String query = D.substring(3);
             PreparedStatement pst=con.prepareStatement(sql);
           pst.setString(1,query);
              rs=pst.executeQuery();
             int i=0;
           while(rs.next())
            {
            Object[] row = new Object[6];
             row[0] = rs.getInt("bill_id");
            row[1] = rs.getString("date");
            String sql2="select first_name, last_name from customers where customer_id=?";
             PreparedStatement pst2=con.prepareStatement(sql2);
            pst2.setString(1,rs.getString("customer_id"));
            rs2=pst2.executeQuery();
                 int k=0;
           while(rs2.next())
            {
            String fn = rs2.getString("first_name");
            String ln = rs2.getString("last_name");
            String name = fn + " " + ln;
            row[2] = name;
         }
           String sql3="select prod_name from products where product_id=?";
           PreparedStatement pst3=con.prepareStatement(sql3);
            pst3.setString(1,rs.getString("product_id"));
            rs3=pst3.executeQuery();
                 int e=0;
                 while(rs3.next())
            {
            String prodnm = rs3.getString("prod_name");
            row[3] = prodnm;
         }
             row[4]= rs.getString("amount");
             row[5]= rs.getString("pay_mode");
                     model.addRow(row);             
         }
            }
            else if (D.startsWith("date:")){
                String sql="select * from bills where date=?";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,D.substring(5));
                rs=pst.executeQuery();
                 int i=0;
           while(rs.next())
            {
            Object[] row = new Object[6];
             row[0] = rs.getInt("bill_id");
            row[1] = rs.getString("date");
            String sql2="select first_name, last_name from customers where customer_id=?";
             PreparedStatement pst2=con.prepareStatement(sql2);
            pst2.setString(1,rs.getString("customer_id"));
            rs2=pst2.executeQuery();
                 int k=0;
           while(rs2.next())
            {
            String fn = rs2.getString("first_name");
            String ln = rs2.getString("last_name");
            String name = fn + " " + ln;
            row[2] = name;
         }
           String sql3="select prod_name from products where product_id=?";
           PreparedStatement pst3=con.prepareStatement(sql3);
            pst3.setString(1,rs.getString("product_id"));
            rs3=pst3.executeQuery();
                 int e=0;
                 while(rs3.next())
            {
            String prodnm = rs3.getString("prod_name");
            row[3] = prodnm;
         }
             row[4]= rs.getString("amount");
             row[5]= rs.getString("pay_mode");
                     model.addRow(row);             
         }
            }
            else {
            JOptionPane.showMessageDialog(this,"Please input a valid search query.");
            }
        }
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }     
}   
    
public void show1()
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try
        {

            Class.forName("java.sql.Driver");

            ResultSet rs=null;

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");

            String sql="select * from bills";

            PreparedStatement pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            String name = "";
            int i=0;
           while(rs.next())
            {
            Object[] row = new Object[6];
        
         
             row[0] = rs.getInt("bill_id");
             row[1] = rs.getString("date");
             int custID = rs.getInt("customer_id");
             String sql2="select first_name, last_name from customers where customer_id=?";
             PreparedStatement pst2=con.prepareStatement(sql2);
                pst2.setString(1,String.valueOf(custID));
                rs2=pst2.executeQuery();
                int p=0;
                while(rs2.next()){
                String fn = rs2.getString("first_name");
                String ln = rs2.getString("last_name");
                row[2]= fn + " " + ln;
                }
             int prodID = rs.getInt("product_id");
             String sql3="select prod_name from products where product_id=?";
             PreparedStatement pst3=con.prepareStatement(sql3);
                pst3.setString(1,String.valueOf(prodID));
                rs3=pst3.executeQuery();
                int l=0;
                while(rs3.next()){
                row[3]= rs3.getString("prod_name");
                }
            row[4]= rs.getString("amount");
            row[5]= rs.getString("pay_mode");
                   
            model.addRow(row);
                    
         }
           }
            catch(Exception e)

        {

            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void billIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billIDActionPerformed

    private void productboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productboxActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    }//GEN-LAST:event_jButton8ActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            /*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
            String sql="insert into bills(bill_id,customer_id,product_id,amount,date,pay_mode) values(?,(Select customer_id from customers where phone=?),"
                    + "(Select product_id from products where prod_name=?),?,?,?)";

            Statement stmt=con.createStatement();
            //ResultSet rs = stmt.executeQuery(sql);
            pst = con.prepareStatement(sql);
            pst.setString(1, billID.getText());
            pst.setString(5,billdate.getText());
            pst.setString(2,customerphone.getText());
            pst.setString(3,productbox.getSelectedItem().toString());
            pst.setString(4,amount.getText());
            pst.setString(6,paymode.getSelectedItem().toString());

            pst.execute();
            JOptionPane.showMessageDialog(null,"Bill Generated Successfully");
            show1();

        }

        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }         // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        billID.setText(model.getValueAt(i,0).toString());
        String name = model.getValueAt(i,2).toString();
        String[] splitStr = name.split("\\s+");
        String firstname=splitStr[0];
        String lastname=splitStr[1];
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            /*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
            String sql="select phone from customers where first_name=? and last_name=?;";

            //Statement stmt=con.createStatement();
            //ResultSet rs = stmt.executeQuery(sql);
            pst = con.prepareStatement(sql);
            pst.setString(1,firstname);
            pst.setString(2,lastname);
            pst.execute();
            int k=0;
           while(rs.next())
            {
             customerphone.setText(rs.getString("phone"));
         }
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
        billdate.setText(model.getValueAt(i,1).toString());
        productbox.setSelectedItem(model.getValueAt(i,3).toString());
        amount.setText(model.getValueAt(i,4).toString());
        paymode.setSelectedItem(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void paymodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymodeActionPerformed

    private void customerphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerphoneActionPerformed

    private void billsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billsearchActionPerformed

    private void suppliersearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersearchboxActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        search_bills();         // TODO add your handling code here:
    }//GEN-LAST:event_suppliersearchboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opt = JOptionPane.showConfirmDialog(
            null,
            "<html>Are you sure you want to logout?<br>You will have to login again.<html>",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (opt==JOptionPane.YES_OPTION){
            new Login().setVisible(true); this.dispose();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton1ActionPerformed
        new Homepage().setVisible(true); this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField amount;
    private javax.swing.JButton backbutton1;
    private javax.swing.JTextField billID;
    private javax.swing.JTextField billdate;
    private javax.swing.JTextField billsearch;
    private javax.swing.JTextField customerphone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> paymode;
    private javax.swing.JComboBox<String> productbox;
    private javax.swing.JButton suppliersearchbox;
    private javax.swing.JLabel userlabel1;
    private javax.swing.JLabel userlabel10;
    private javax.swing.JLabel userlabel11;
    private javax.swing.JLabel userlabel12;
    private javax.swing.JLabel userlabel2;
    private javax.swing.JLabel userlabel3;
    private javax.swing.JLabel userlabel4;
    private javax.swing.JLabel userlabel5;
    private javax.swing.JLabel userlabel6;
    private javax.swing.JLabel userlabel7;
    private javax.swing.JLabel userlabel8;
    private javax.swing.JLabel userlabel9;
    // End of variables declaration//GEN-END:variables
}
