/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs.ia.music_mng_sys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lakshya
 */
public class customers_page extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
Statement stmt=null;
    /**
     * Creates new form customers_page
     */
    public customers_page() {
        initComponents();
        show1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userlabel4 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        userlabel1 = new javax.swing.JLabel();
        userlabel2 = new javax.swing.JLabel();
        userlabel3 = new javax.swing.JLabel();
        custphone = new javax.swing.JTextField();
        custID = new javax.swing.JTextField();
        custaddress = new javax.swing.JTextField();
        custname = new javax.swing.JTextField();
        editbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        userlabel5 = new javax.swing.JLabel();
        custemail = new javax.swing.JTextField();
        userlabel6 = new javax.swing.JLabel();
        custname1 = new javax.swing.JTextField();
        backbutton1 = new javax.swing.JButton();
        custsearchtext = new javax.swing.JTextField();
        suppliersearchbox = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 540));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Email", "Address", "Phone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        userlabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel4.setText("Phone:");

        addButton.setText("ADD");
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        userlabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel1.setText("Address:");

        userlabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel2.setText("ID:");

        userlabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel3.setText("First name:");

        custphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custphoneActionPerformed(evt);
            }
        });

        custID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDActionPerformed(evt);
            }
        });

        custaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custaddressActionPerformed(evt);
            }
        });

        custname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custnameActionPerformed(evt);
            }
        });

        editbutton.setText("UPDATE");
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });

        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });

        userlabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel5.setText("Email:");

        custemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custemailActionPerformed(evt);
            }
        });

        userlabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel6.setText("Last name:");

        custname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custname1ActionPerformed(evt);
            }
        });

        backbutton1.setText("BACK");
        backbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbutton1MouseClicked(evt);
            }
        });

        custsearchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custsearchtextActionPerformed(evt);
            }
        });

        suppliersearchbox.setText("SEARCH");
        suppliersearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersearchboxActionPerformed(evt);
            }
        });

        jButton1.setText("SIGN OUT");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(custsearchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(suppliersearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(userlabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(custname1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(userlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(custemail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(userlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(userlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(custphone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(custaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(userlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userlabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custname1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userlabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custemail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userlabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(custphone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suppliersearchbox)
                                    .addComponent(custsearchtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(backbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void search_customer(){
DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                 model.setRowCount(0);
              String D=custsearchtext.getText();
        try
        {
            Class.forName("java.sql.Driver");

            ResultSet rs=null;

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            if (D.startsWith("id:")){
              String sql="select * from customers where customer_id=?";
                String query = D.substring(3);
             PreparedStatement pst=con.prepareStatement(sql);
           pst.setString(1,query);
              rs=pst.executeQuery();
             int i=0;
           while(rs.next())
            {
            Object[] row = new Object[5];
             row[0] = rs.getInt("customer_id");
            String firstname = rs.getString("first_name");
            String lastname = rs.getString("last_name");
            row[1] = firstname + " " + lastname;
            row[2]= rs.getString("email");
             row[3]= rs.getString("address");
             row[4]= rs.getString("phone");
                     model.addRow(row);             
         }
            }
            else if (D.startsWith("name:")){
                String[] splitStr = D.split("\\s+");
                String firstname=(splitStr[0]).substring(5);
                String lastname=splitStr[1];
                String sql="select * from customers where first_name=? and last_name=?";
                PreparedStatement pst=con.prepareStatement(sql);
                pst.setString(1,firstname);
                    pst.setString(2,lastname);
                rs=pst.executeQuery();
                 int i=0;
           while(rs.next())
            {
            Object[] row = new Object[5];
             row[0] = rs.getInt("customer_id");
            String fn = rs.getString("first_name");
            String ln = rs.getString("last_name");
            row[1]=fn + " " + ln;
            row[2]= rs.getString("email");
             row[3]= rs.getString("address");
             row[4]= rs.getString("phone");
                     model.addRow(row);             
         }
            }
            else {
            JOptionPane.showMessageDialog(this,"Please input a valid search query.");
            }
        }
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }     
}   
    
    
public void show1()
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       
        try

        {

            Class.forName("java.sql.Driver");

            ResultSet rs=null;

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");

            String sql="select * from customers";

            PreparedStatement pst=con.prepareStatement(sql);

       
          

            rs=pst.executeQuery();
            int i=0;
           while(rs.next())
            {
            Object[] row = new Object[5];
        
         
             row[0] = rs.getInt("customer_id");
             String firstname = rs.getString("first_name");
             String lastname = rs.getString("last_name");
            row[1]= firstname + " " + lastname;
            row[2]= rs.getString("email");
            row[3]= rs.getString("address");
            row[4]= rs.getString("phone");
                   
                     model.addRow(row);
                    
         }
           }
            catch(Exception e)

        {

            JOptionPane.showMessageDialog(null,e);

        
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        custID.setText(model.getValueAt(i,0).toString());
        String name = model.getValueAt(i,1).toString();
        String[] splitStr = name.split("\\s+");
        String firstname=splitStr[0];
        String lastname=splitStr[1];
        custname.setText(firstname);
        custname1.setText(lastname);
        custemail.setText(model.getValueAt(i,2).toString());
        custaddress.setText(model.getValueAt(i,3).toString());
        custphone.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            /*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
            String sql="insert into customers(customer_id,first_name,last_name,email,address,phone) values(?,?,?,?,?,?)";

            Statement stmt=con.createStatement();
            // ResultSet rs = pst.executeQuery(sql);
            pst = con.prepareStatement(sql);
            pst.setString(1, custID.getText());
            pst.setString(2,custname.getText());
            pst.setString(3,custname1.getText());
            pst.setString(4,custemail.getText());
            pst.setString(5,custaddress.getText());
            pst.setString(6,custphone.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null,"Information Added");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            show1();
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void custphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custphoneActionPerformed

    private void custIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDActionPerformed

    private void custaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custaddressActionPerformed

    private void custnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custnameActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        String Id = custID.getText();
        String firstname = custname.getText();
        String lastname = custname1.getText();
        String email = custemail.getText();
        String Address = custaddress.getText();
        String Phone = custphone.getText();


        try {
            Class.forName("java.sql.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            /*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
            String sql="update customers set first_name=?, last_name=?, email=?, address= ?, phone=? where customer_id= ?;";

            //Statement stmt=con.createStatement();
            //ResultSet rs = stmt.executeQuery(sql);
            pst = con.prepareStatement(sql);
            //pst.setString(1, jTextField1.getText());
            pst.setString(1,firstname);
            pst.setString(2,lastname);
            pst.setString(3,email);
            pst.setString(4,Address);
            pst.setString(5,Phone);

            pst.setString(6,Id);
            int i=pst.executeUpdate(); 
            if(i>0)// Check if there are any records updated
            {
                JOptionPane.showMessageDialog(null,"Data Updated Successfully!!!");
                custID.setText("");
                custname.setText("");
                custname1.setText("");
                custemail.setText("");
                custaddress.setText("");
                custphone.setText("");

            }
            else//Give update error if no records were updated
            {
                JOptionPane.showMessageDialog(null,"Error Updating Data!!!");
            }
            //JOptionPane.showMessageDialog(null,"Database updated");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            show1();
            //new stable().setVisible(true);
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }           // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_editbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            String sql="delete from customers where customer_id=?;";
            pst=con.prepareStatement(sql);
            pst.setString(1, custID.getText());
            int i=pst.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null,"Data Deleted Successfully!!!");
                custID.setText("");
                custname.setText("");
                custname1.setText("");
                custemail.setText("");
                custaddress.setText("");
                custphone.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error Deleting Data!!!");
            }
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            show1();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void custemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custemailActionPerformed

    private void custname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custname1ActionPerformed

    private void backbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbutton1MouseClicked
        new Homepage().setVisible(true); this.dispose();
    }//GEN-LAST:event_backbutton1MouseClicked

    private void custsearchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custsearchtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custsearchtextActionPerformed

    private void suppliersearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersearchboxActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        search_customer();         // TODO add your handling code here:
    }//GEN-LAST:event_suppliersearchboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opt = JOptionPane.showConfirmDialog(
            null,
            "<html>Are you sure you want to logout?<br>You will have to login again.<html>",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (opt==JOptionPane.YES_OPTION){
            new Login().setVisible(true); this.dispose();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customers_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customers_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customers_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customers_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customers_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backbutton1;
    private javax.swing.JTextField custID;
    private javax.swing.JTextField custaddress;
    private javax.swing.JTextField custemail;
    private javax.swing.JTextField custname;
    private javax.swing.JTextField custname1;
    private javax.swing.JTextField custphone;
    private javax.swing.JTextField custsearchtext;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton suppliersearchbox;
    private javax.swing.JLabel userlabel1;
    private javax.swing.JLabel userlabel2;
    private javax.swing.JLabel userlabel3;
    private javax.swing.JLabel userlabel4;
    private javax.swing.JLabel userlabel5;
    private javax.swing.JLabel userlabel6;
    // End of variables declaration//GEN-END:variables
}
