/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs.ia.music_mng_sys;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lakshya
 */
public class purchases_page extends javax.swing.JFrame {
Connection con=null;
PreparedStatement pst=null;
ResultSet rs=null;
ResultSet rs2=null;
ResultSet rs3=null;
    /**
     * Creates new form purchases_page
     */
    public purchases_page() {
        initComponents();
        show1();
        
        try
        {
            Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            String sql="select * from products";

            PreparedStatement pst=con.prepareStatement(sql);

            rs=pst.executeQuery();
            int i=0;
           while(rs.next())
            {
                String name= rs.getString("prod_name");
                productbox.addItem(name);
                    
         }
           productbox.setSelectedItem("");
           }
            catch(Exception e)

        {

            JOptionPane.showMessageDialog(null,e);
        }
        
        try
        {
            Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            String sql="select * from suppliers";

            PreparedStatement pst=con.prepareStatement(sql);

            rs=pst.executeQuery();
            int i=0;
           while(rs.next())
            {
                String name= rs.getString("supplier_name");
                productbox1.addItem(name);
                    
         }
           productbox1.setSelectedItem("");
           }
            catch(Exception e)

        {

            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userlabel12 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        cost = new javax.swing.JTextField();
        purchaseID = new javax.swing.JTextField();
        purchasedate = new javax.swing.JTextField();
        userlabel8 = new javax.swing.JLabel();
        userlabel9 = new javax.swing.JLabel();
        userlabel10 = new javax.swing.JLabel();
        userlabel11 = new javax.swing.JLabel();
        productbox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        backbutton1 = new javax.swing.JButton();
        purchasesearch = new javax.swing.JTextField();
        suppliersearchbox = new javax.swing.JButton();
        userlabel13 = new javax.swing.JLabel();
        productbox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Purchase ID", "Date", "Product name", "Supplier", "Quantity", "Total cost"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        userlabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel12.setText("Quantity:");

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        addbutton.setText("ADD");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        purchaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseIDActionPerformed(evt);
            }
        });

        userlabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel8.setText("Total cost:");

        userlabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel9.setText("Purchase date:");

        userlabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel10.setText("Purchase ID:");

        userlabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel11.setText("Product name:");

        productbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productboxActionPerformed(evt);
            }
        });

        jButton1.setText("SIGN OUT");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backbutton1.setText("BACK");
        backbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton1ActionPerformed(evt);
            }
        });

        purchasesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchasesearchActionPerformed(evt);
            }
        });

        suppliersearchbox.setText("SEARCH");
        suppliersearchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersearchboxActionPerformed(evt);
            }
        });

        userlabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userlabel13.setText("Supplier name:");

        productbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productbox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(purchasesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(suppliersearchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userlabel12)
                                    .addComponent(userlabel8))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(quantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(cost, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userlabel10)
                                    .addComponent(userlabel11)
                                    .addComponent(userlabel9))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchaseID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purchasedate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(userlabel13)
                                .addGap(56, 56, 56)
                                .addComponent(productbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backbutton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(suppliersearchbox)
                                .addComponent(purchasesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(purchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(purchasedate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userlabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userlabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void search_purchases(){
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                 model.setRowCount(0);
              String D=purchasesearch.getText();
        try
        {
            Class.forName("java.sql.Driver");

            ResultSet rs=null;
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            if (D.startsWith("id:")){
              String sql="select * from purchases where purchase_id=?";
                String query = D.substring(3);
             PreparedStatement pst=con.prepareStatement(sql);
           pst.setString(1,query);
              rs=pst.executeQuery();
             int i=0;
           while(rs.next())
            {
            Object[] row = new Object[6];
             row[0] = rs.getInt("purchase_id");
            row[1] = rs.getString("date");
           String sql2="select prod_name from products where product_id=?";
           PreparedStatement pst2=con.prepareStatement(sql2);
            pst2.setString(1,rs.getString("product_id"));
            rs2=pst2.executeQuery();
                 int e=0;
                 while(rs2.next())
            {
            row[2] = rs2.getString("prod_name");
         }
                 String sql3="select supplier_name from suppliers where supplier_id=?";
           PreparedStatement pst3=con.prepareStatement(sql3);
            pst3.setString(1,rs.getString("supplier_id"));
            rs3=pst3.executeQuery();
                 int k=0;
                 while(rs3.next())
            {
            row[3] = rs3.getString("supplier_name");
            }
             row[4]= rs.getString("quantity");
             row[5]= rs.getString("amount");
                     model.addRow(row);             
         }
            }
            else if (D.startsWith("date:")){
                String query = D.substring(5);
                String sql="select * from purchases where date=?";
                PreparedStatement pst=con.prepareStatement(sql);
           pst.setString(1,query);
           rs=pst.executeQuery();
                 int i=0;
           while(rs.next())
            {
            Object[] row = new Object[5];
             row[0] = rs.getInt("id");
            String fn = rs.getString("first_name");
            String ln = rs.getString("last_name");
            row[1]=fn + " " + ln;
            row[2]= rs.getString("email");
             row[3]= rs.getString("address");
             row[4]= rs.getString("phone");
                     model.addRow(row);             
         }
            }
            else {
            JOptionPane.showMessageDialog(this,"Please input a valid search query.");
            }
        }
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }     
}   
    
    public void show1()
    {
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try
        {

            Class.forName("java.sql.Driver");

            ResultSet rs=null;

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");

            String sql="select * from purchases";

            PreparedStatement pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            String name = "";
            int i=0;
           while(rs.next())
            {
            Object[] row = new Object[6];
        
         
             row[0] = rs.getInt("purchase_id");
             row[1] = rs.getString("date");
             int prodID = rs.getInt("product_id");
             String sql2="select prod_name from products where product_id=?";
             PreparedStatement pst2=con.prepareStatement(sql2);
                pst2.setString(1,String.valueOf(prodID));
                rs2=pst2.executeQuery();
                int l=0;
                while(rs2.next()){
                row[2]= rs2.getString("prod_name");
                }
                int suppID = rs.getInt("supplier_id");
             String sql3="select supplier_name from suppliers where supplier_id=?";
             PreparedStatement pst3=con.prepareStatement(sql3);
                pst3.setString(1,String.valueOf(suppID));
                rs3=pst3.executeQuery();
                int w=0;
                while(rs3.next()){
                row[3]= rs3.getString("supplier_name");
                }
            row[5]= rs.getString("amount");
            row[4]= rs.getString("quantity");
            model.addRow(row);
                    
         }
           }
            catch(Exception e)

        {

            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        purchaseID.setText(model.getValueAt(i,0).toString());
        quantity.setText(model.getValueAt(i,3).toString());
        purchasedate.setText(model.getValueAt(i,1).toString());
        productbox.setSelectedItem(model.getValueAt(i,2).toString());
        cost.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","abc123456");
            /*As we are creating a connection on a local computer we will write the url as jdbc:mysql://localhost:3306 */
            String sql="insert into purchases(purchase_id,product_id,supplier_id, quantity,amount,date) "
                    + "values(?,(Select product_id from products where prod_name=?),(Select supplier_id from suppliers where supplier_name=?),?,?,?)";

            Statement stmt=con.createStatement();
            //ResultSet rs = stmt.executeQuery(sql);
            pst = con.prepareStatement(sql);
            pst.setString(1, purchaseID.getText());
            pst.setString(6,purchasedate.getText());
            pst.setString(4,quantity.getText());
            pst.setString(2,productbox.getSelectedItem().toString());
            pst.setString(3,productbox1.getSelectedItem().toString());
            pst.setString(5,cost.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null,"Purchase transaction listed successfully.");
            show1();
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }         // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_addbuttonActionPerformed

    private void purchaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseIDActionPerformed

    private void productboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int opt = JOptionPane.showConfirmDialog(
            null,
            "<html>Are you sure you want to logout?<br>You will have to login again.<html>",
            "Confirmation",
            JOptionPane.YES_NO_OPTION);
        if (opt==JOptionPane.YES_OPTION){
            new Login().setVisible(true); this.dispose();
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton1ActionPerformed
        new Homepage().setVisible(true); this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backbutton1ActionPerformed

    private void purchasesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchasesearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchasesearchActionPerformed

    private void suppliersearchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersearchboxActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        search_purchases();         // TODO add your handling code here:
    }//GEN-LAST:event_suppliersearchboxActionPerformed

    private void productbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchases_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchases_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchases_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchases_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchases_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton backbutton1;
    private javax.swing.JTextField cost;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> productbox;
    private javax.swing.JComboBox<String> productbox1;
    private javax.swing.JTextField purchaseID;
    private javax.swing.JTextField purchasedate;
    private javax.swing.JTextField purchasesearch;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton suppliersearchbox;
    private javax.swing.JLabel userlabel10;
    private javax.swing.JLabel userlabel11;
    private javax.swing.JLabel userlabel12;
    private javax.swing.JLabel userlabel13;
    private javax.swing.JLabel userlabel8;
    private javax.swing.JLabel userlabel9;
    // End of variables declaration//GEN-END:variables
}
